# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      #- name: Copy Contents
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.LOGIN }}
      #    key: ${{ secrets.PASSWORD }}
      #   port: ${{ secrets.PORT }}

      - run: echo "${{ secrets.HOST }} ${{ secrets.LOGIN }}"
